name: Daily Commit

on:
  schedule:
    - cron: '15 3 * * *'  # Runs daily at 03:15 UTC
  workflow_dispatch:      # Allows manual triggering

jobs:
  commit-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make a change
        run: |
          echo "Daily update: $(date)" >> daily-log.txt

      - name: Commit and push changes - 24f2006326@ds.study.iitm.ac.in
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Daily commit: $(date)"
          git push
